import Head from 'next/head';

import { useThemeStore } from '@/shared/store';
import { HomeStyles } from '@/src/styles/Home.css';
import { ThemeColor, themeColorEnum } from '@/theme/config';

export default function Home() {
	const themeColor = useThemeStore(s => s.themeColorCurrent);
	const changeThemeColor = useThemeStore(s => s.changeThemeColor);
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div className={HomeStyles.layout}>
				<select
					name='s'
					id='s'
					value={themeColor}
					onChange={e => {
						const value = e.target.value as ThemeColor;
						// console.log(value);
						// MyLocalStorageRepo().save(localStorageKeys.themeColor, value);
						// document.documentElement.classList.value = themeClass[value];
						changeThemeColor(value);
					}}
				>
					{themeColorEnum.iterable.map(theme => (
						<option key={theme} value={theme}>
							{theme}
						</option>
					))}
				</select>
			</div>
		</>
	);
}
