import Head from 'next/head';

import { Button } from '@/shared/components';
import { useThemeStore } from '@/shared/store';
import { ThemeColor, themeColorEnum } from '@/theme/config';

export default function Theme() {
	const themeColor = useThemeStore(s => s.themeColorCurrent);
	const changeThemeColor = useThemeStore(s => s.changeThemeColor);
	return (
		// <div className={merriweather.className}>
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<section>
				<div>
					<select
						name='s'
						id='s'
						value={themeColor}
						onChange={e => {
							const value = e.target.value as ThemeColor;

							// MyLocalStorageRepo().save(localStorageKeys.themeColor, value);
							// document.documentElement.classList.value = themeClass[value];
							changeThemeColor(value);
						}}
					>
						{themeColorEnum.iterable.map(theme => (
							<option key={theme} value={theme}>
								{theme}
							</option>
						))}
					</select>
				</div>

				<h2>Solid</h2>
				<div style={{ display: 'flex', gap: '0.5rem' }}>
					<Button colorScheme='primary' variant='solid'>
						Button
					</Button>
					<Button colorScheme='primary' variant='solid' disabled>
						Button
					</Button>
					<Button colorScheme='secondary' variant='solid'>
						Button
					</Button>
					<Button colorScheme='secondary' variant='solid' disabled>
						Button
					</Button>
				</div>

				<h2>Outline</h2>
				<div style={{ display: 'flex', gap: '0.5rem' }}>
					<Button colorScheme='primary' variant='outline'>
						Button
					</Button>
					<Button colorScheme='primary' variant='outline' disabled>
						Button
					</Button>
					<Button colorScheme='secondary' variant='outline'>
						Button
					</Button>
					<Button colorScheme='secondary' variant='outline' disabled>
						Button
					</Button>
				</div>

				<h2>Ghost</h2>
				<div style={{ display: 'flex', gap: '0.5rem' }}>
					<Button colorScheme='primary' variant='ghost'>
						Button
					</Button>
					<Button colorScheme='primary' variant='ghost' disabled>
						Button
					</Button>
					<Button colorScheme='secondary' variant='ghost'>
						Button
					</Button>
					<Button colorScheme='secondary' variant='ghost' disabled>
						Button
					</Button>
				</div>

				<h2>Link</h2>
				<div style={{ display: 'flex', gap: '0.5rem' }}>
					<Button colorScheme='primary' variant='link'>
						Button
					</Button>
					<Button colorScheme='primary' variant='link' disabled>
						Button
					</Button>
					<Button colorScheme='secondary' variant='link'>
						Button
					</Button>

					<Button colorScheme='secondary' variant='link' disabled>
						Button
					</Button>
				</div>

				<h2>Unstyled</h2>
				<div style={{ display: 'flex', gap: '0.5rem' }}>
					<Button variant='unstyled'>Button</Button>
				</div>
			</section>
		</>
	);
}
