import { Lora } from '@next/font/google';
import Header from 'components/header/Header';
import Head from 'next/head';
import styled from 'styled-components';

const lora = Lora({
	weight: ['400', '700'],
});

const MainStyle = styled.main`
	padding: 2rem 0;
	display: flex;
	justify-content: space-between;
	gap: 4rem;
`;

export default function Home() {
	return (
		<>
			<Head>
				<title>Gentleman Programing book</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<MainStyle>
				<Header />
				<section
					className={lora.className}
					style={{ fontSize: '22px', letterSpacing: '1px', lineHeight: '3rem' }}
				>
					<h2>Lorem ipsum dolor.</h2>
					<p>
						Lorem, ipsum dolor sit amet consectetur adipisicing elit. Obcaecati
						nam laborum repudiandae nemo quos. Nesciunt deleniti beatae ipsum
						impedit et suscipit quos voluptas vel iste possimus earum, explicabo
						sunt delectus. Lorem ipsum dolor sit amet consectetur adipisicing
						elit. Totam eaque illo id alias recusandae, accusamus temporibus
						iusto animi in beatae quo nulla dolorem deleniti dicta asperiores
						unde ab autem nam? Lorem ipsum dolor sit amet consectetur
						adipisicing elit. Debitis in placeat officia nihil, perspiciatis
						nostrum dolore rem culpa? Dicta cupiditate corrupti earum vel sunt
						autem a, sit odio consectetur quis.
					</p>
				</section>
			</MainStyle>
		</>
	);
}

